### ISSUE TITLE
Cannot read property 'target' of undefined 

### ISSUE THREAD

**Issue by ghost** [vicentereig/bootstrap-modal-rails#4]
Hi,
I get the error "Uncaught TypeError: Cannot read property 'target' of undefined". Modal gets loaded but when I try to close it it throws out this error and page gets locked. Its these lines on modelmanager js. I guess I have bootstrap namespace elements so I tried removing the function but it made other parts fail..finally removed "e" and the condition and it worked but this time modal dissapears onclick..

```
    // make sure the event target is the modal itself in order to prevent
// other components such as tabsfrom triggering the modal manager.
// if Boostsrap namespaced events, this would not be needed.
function targetIsSelf(callback){
    return function (e) {
          if (this === e.target){
            return callback.apply(this, arguments);
                }
            }
        }
```

My modal

```
   #app-score.modal.hide.fade{'aria-labelledby' => t('whatis_appscore'), 'aria-hidden' => true }
    .modal-header
      %button.close{ type: 'button', data: { dismiss: 'modal' }, 'aria-hidden' => true } &times;
      %h3= t('whatis_appscore')
      .modal-body
```

How I call modal

```
  %medium.inline-block.why-facebook= link_to t('why_facebook'), '#why-facebook', data: { toggle:     'modal' }
```

**Comment by vicentereig** [comment]
@canercak Seems like an issue on the original library. This asset gem is just a wrapper to deliver their JS assets. Would you mind to repost the issue at https://github.com/jschr/bootstrap-modal/issues?

**Comment by ghost** [comment]
you know its just a buggy plugin..there are 80 other open issues and most of them seem like bugs..I won't use it..thank you..
