### ISSUE TITLE
You should update the readme

### ISSUE THREAD

**Issue by pablosalgadom** [vicentereig/bootstrap-modal-rails#6]
Hello everyone, i'm happily using this gem, but i had some trouble at first because of the outdated readme which says that in the gemfile i have to do this:

```
group :assets do
 gem 'bootstrap-modal-rails'
end
```

But that doesn't work in Rails 4, so i had to remove some code and let it like this:

```
gem 'bootstrap-modal-rails'
```

And it worked perfectly, i'm saying this because someone who is new in rails could thought that the gem has some bugs.

The same thing happens for the application.css, where you must write it different at the beginning and also add another css file before the bootstrap-modal, like this:

```
 *= require bootstrap-modal-bs3patch
 *= require bootstrap-modal
```

Hope it helps!

**Comment by laitanner** [comment]
Thanks, solved my issues! I think bs3patch is just for those using bootstrap 3 in conjunction with jschr's bootstrap modal. The `*=` is only if you are commenting using `/*` and `*/`. Otherwise, I think `//` works fne.

**Comment by vicentereig** [comment]
@laitanner @pablosalgadom If you guys want to submit a PR I'll be glad to review it and merge it. Thanks!

**Comment by pablosalgadom** [comment]
just did the pull request, hope i have done properly >.<!!
