### ISSUE TITLE
Change readme

### ISSUE THREAD

**Issue by westonganger** [vicentereig/bootstrap-modal-rails#8]
This issue: https://github.com/jschr/bootstrap-modal/issues/115

In your application stylesheet if you require bootstrap-modal before tree you will get margin-top and height issues. You should mention to require it after tree or by using one of the method described in the issue. This really needs to be in the readme.

**Comment by vicentereig** [comment]
Hi @westonganger, thanks for the heads up! If you want to submit a PR, I'll be glad to review it and merge it.

Thank you,
Vicente.

**Comment by westonganger** [comment]
Sure, I submitted the PR
